name: Build & Push (no deploy)

on:
  push:
    branches: [ main, release/** ]
    paths: [ "front/**", "front/Dockerfile", ".github/workflows/build.yml" ]

jobs:
  build_and_push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with: { fetch-depth: 0 }

      - name: Compute version (NBGV)
        id: nbgv
        uses: dotnet/nbgv@v0.4

      - name: Echo version & guard
        run: |
          echo "SemVer2=${{ steps.nbgv.outputs.SemVer2 }}"
          echo "SHA=${{ steps.nbgv.outputs.GitCommitIdShort }}"
          test -n "${{ steps.nbgv.outputs.SemVer2 }}" || { echo "Empty version!"; exit 1; }

      - name: Docker login
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build & push
        env:
          IMAGE: louis404/beeshop-front
          VER: ${{ steps.nbgv.outputs.SemVer2 }}
          SHA: ${{ steps.nbgv.outputs.GitCommitIdShort }}
          REF: ${{ github.ref }}
        run: |
          CLEAN_VER="${VER%%+*}"   # retire le +gXXXX
          echo "Build $IMAGE:$CLEAN_VER"

          DOCKER_BUILDKIT=1 docker build -t $IMAGE:$CLEAN_VER .
          docker tag $IMAGE:$CLEAN_VER $IMAGE:sha-$SHA

          if [[ "$REF" == refs/heads/release/* ]]; then
            docker tag $IMAGE:$CLEAN_VER $IMAGE:rc
          fi

          docker push $IMAGE:$CLEAN_VER
          docker push $IMAGE:sha-$SHA
          if [[ "$REF" == refs/heads/release/* ]]; then
            docker push $IMAGE:rc
          fi