name: CD - Front (Docker Build/Push + Deploy)

on:
  push:
    branches: [ main, release/** ]
    paths: [ "front/**", ".github/workflows/cd.yml", "front/Dockerfile" ]
  workflow_dispatch: {}

jobs:
  build_and_push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Ensure jq is available
        run: sudo apt-get update && sudo apt-get install -y jq

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set version
        id: vars
        run: |
          VERSION=$(jq -r .version package.json)
          echo "VERSION=$VERSION" >> $GITHUB_OUTPUT


      - name: Build Docker image
        run: |
          docker build -t louis404/beeshop-front:${{ steps.vars.outputs.VERSION }} .
          docker tag louis404/beeshop-front:${{ steps.vars.outputs.VERSION }} louis404/beeshop-front:latest

      - name: Push Docker image
        run: |
          docker push louis404/beeshop-front:${{ steps.vars.outputs.VERSION }}
          docker push louis404/beeshop-front:latest

  deploy:
    needs: build_and_push
    if: github.ref_name == 'main'
    runs-on: ubuntu-latest
    steps:
      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.DEPLOY_HOST }}
          username: ${{ secrets.DEPLOY_USER }}
          key: ${{ secrets.DEPLOY_KEY }}
          script: |
            set -e
            echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin
            cd /home/ubuntu/beeshop
            docker stop beeshop-front || true
            docker rm beeshop-front || true
            docker compose pull front
            docker compose up -d front
            docker image prune -f

