name: CD - Build and Deploy Front

on:
  push:
    branches:
      - main
      - release/**

jobs:
  build_and_push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set version
        id: vars
        run: |
          VERSION=$(cat package.json | jq -r .version)
          echo "VERSION=$VERSION" >> $GITHUB_OUTPUT

      - name: Build Docker image
        run: |
          docker build -t louis404/beeshop-front:${{ steps.vars.outputs.VERSION }} .
          docker tag louis404/beeshop-front:${{ steps.vars.outputs.VERSION }} louis404/beeshop-front:latest

      - name: Push Docker image
        run: |
          docker push louis404/beeshop-front:${{ steps.vars.outputs.VERSION }}
          docker push louis404/beeshop-front:latest
