name: Build and Test Front Nuxt with pnpm

on:
  push:
    branches:
      - main
      - develop

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        cache: 'pnpm'

    - name: Install pnpm
      run: npm install -g pnpm@8

    - name: Install dependencies
      run: pnpm install

    - name: Build the app
      run: pnpm build

    - name: Run unit tests
      run: pnpm test

    - name: Archive production build
      uses: actions/upload-artifact@v3
      with:
        name: nuxt-dist
        path: ./.output
