name: Build and Test Front Nuxt with pnpm

on:
  push:
    branches:
      - main
      - develop

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Install pnpm
      uses: pnpm/action-setup@v2
      with:
        version: 8

    - name: Check pnpm version
      run: pnpm --version

    - name: Install dependencies
      run: npm_config_build_from_source=true pnpm install

    - name: Build the app
      run: pnpm build

    - name: Run unit tests
      run: pnpm test

    - name: Archive production build
      uses: actions/upload-artifact@v4
      with:
        name: nuxt-dist
        path: ./.output
